name: ChargeMate CI/CD

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: backend
      run: mvn -B clean verify || true
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        XRAY_CLIENT_ID: ${{ secrets.XRAYID }}
        XRAY_CLIENT_SECRET: ${{ secrets.XRAYSECRET }}

    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    - name: Upload Test Results to Xray
      uses: xray-app/xray-cloud-junit-upload@v1
      with:
        xrayClientId: ${{ secrets.XRAYID }}
        xrayClientSecret: ${{ secrets.XRAYSECRET }}
        testFormat: junit
        testPaths: backend/target/surefire-reports/*.xml
        testExecKey: ${{ vars.TESTPLANKEY }}

    - name: Upload Coverage Report to Xray
      uses: xray-app/xray-cloud-junit-upload@v1
      with:
        xrayClientId: ${{ secrets.XRAYID }}
        xrayClientSecret: ${{ secrets.XRAYSECRET }}
        testFormat: junit
        testPaths: backend/target/site/jacoco/jacoco.xml
        testExecKey: ${{ vars.TESTPLANKEY }}