name: Xray Test Results

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]
    types: [opened, synchronize, reopened]

jobs:
  xray:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build and run unit tests
      run: mvn -B clean package --file backend/pom.xml

    - name: Run integration tests
      run: mvn -B verify --file backend/pom.xml

    - name: List test reports
      run: ls -l backend/target/surefire-reports || echo "No reports found"

    - name: List all in backend/target
      run: ls -lR backend/target || echo "No target dir"

    - name: List workspace
      run: ls -lR .

    - name: Debug Surefire output
      run: |
        echo "Conteúdo de backend/target/surefire-reports:"
        ls -l backend/target/surefire-reports || echo "Diretório não existe"
        echo "Conteúdo de backend/target:"
        ls -l backend/target || echo "Diretório não existe"
        echo "Conteúdo do workspace:"
        ls -l .

    - name: Push results to Xray on Jira Cloud
      if: always()
      env:
        XRAYCLOUD_CLIENT_ID: ${{ secrets.XRAYID }}
        XRAYCLOUD_CLIENT_SECRET: ${{ secrets.XRAYSECRET }}
        XRAY_PROJECT_KEY: ${{ vars.XRAY_PROJECT_KEY }}
        TESTPLANKEY: ${{ vars.TESTPLANKEY }}
        REPORTFILE: ${{ vars.REPORTFILE }}
      run: |
        mvn -f backend/pom.xml \
          -Dxray.clientId=${{ env.XRAYCLOUD_CLIENT_ID }} \
          -Dxray.clientSecret=${{ env.XRAYCLOUD_CLIENT_SECRET }} \
          -Dxray.projectKey=${{ env.XRAY_PROJECT_KEY }} \
          -Dxray.testPlanKey=${{ env.TESTPLANKEY }} \
          -Dxray.reportFile=${{ env.REPORTFILE }} \
          xray:import-results 